-- 1. CLEANUP (Prevents "Duplicate Entry" errors on restart)
-- We disable referential integrity so we can truncate tables with foreign keys.
SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE result;
TRUNCATE TABLE question;
TRUNCATE TABLE quiz;
TRUNCATE TABLE student;
TRUNCATE TABLE teacher;
SET REFERENTIAL_INTEGRITY TRUE;

-- 2. INSERT TEACHER
-- Note: 'id' is auto-generated by Hibernate, so we don't include it here.
INSERT INTO teacher (name, tchrid, password)
VALUES ('ak', '1', 'ak');

-- 3. INSERT STUDENT
INSERT INTO student (name, roll_no, password)
VALUES ('vv', '1', 'ak');

-- 4. INSERT INITIAL QUIZ (So the dashboard isn't empty)
-- We manually set ID 1 here so we can link questions to it.
INSERT INTO quiz (id, title)
VALUES (1, 'Java OOP & Basics');

-- 5. INSERT SAMPLE QUESTIONS
-- correct_option is 0=A, 1=B, 2=C, 3=D
INSERT INTO question (question_text, correct_option, quiz_id)
VALUES ('Which keyword is used to inherit a class in Java?', 1, 1); -- Option B: extends

INSERT INTO question (question_text, correct_option, quiz_id)
VALUES ('Which of these is NOT a pillar of OOP?', 3, 1); -- Option D: Compilation

-- 6. (Optional) SEED A RESULT
-- This lets you test the 'View Results' logic immediately.
INSERT INTO result (student_name, score, total_marks, quiz_id)
VALUES ('Akash', 2, 2, 1);